### ISSUE TITLE
Documentation doesn't work through HTTPS

### ISSUE THREAD

**Issue by braiden-vasco** [litaio/docs.lita.io#9]
Documentation doesn't work through HTTPS. This is not comfortable for most users because of widespread practice of modern browsers of redirection HTTP to HTTPS. Inexperienced users don't have access to site at all.

**Comment by jimmycuadra** [comment]
This is a limitation of GitHub Pages, where the docs are hosted. In the hopefully-near-future all the lita.io sites will be moved to different infrastructure at which point they will all be served over HTTPS.
